### ISSUE TITLE
Comparison List Type - Anilist Media List

### ISSUE THREAD

**Issue by robert-huang** [AlexPolGit/Super-Sorter#9]
Options:
- [x] Manga/Anime

Filters:
- User specific attributes
  - [x] watch date
  - [x] score
  - [x] status
- Media attributes
  - [x] genres
  - [x] format (tv/movie/etc / manga/ln/etc)
  - [x] tags
  - [x] airing date
  - [x] favourites
  - [x] average score

**Comment by AlexPolGit** [comment]
Probably not gonna do tags as part of this issue since it seems like a bit too much work for not much benefit. Could maybe do it as part of a different PR later.
